$replacements = @(
    @('CODE_00DDAB', 'Graphics_RenderTile'),
    @('CODE_00DDF5', 'Graphics_InitializeTileBuffer'),
    @('CODE_00DE0C', 'Graphics_TileComplete'),
    @('CODE_00DE0F', 'Graphics_ProcessSprite'),
    @('CODE_00DF43', 'Graphics_ClearBuffer'),
    @('CODE_00DF93', 'Graphics_CopyTileData'),
    @('CODE_00DFBE', 'Graphics_ProcessCopy'),
    @('CODE_00DFC2', 'Graphics_CopyLoop'),
    @('CODE_00DFCE', 'Graphics_CalculateSize'),
    @('CODE_00DFEB', 'Graphics_NextRow'),
    @('CODE_00DFFA', 'Graphics_SetupTransfer'),
    @('CODE_00E00E', 'Graphics_TransferLoop'),
    @('CODE_00E036', 'Graphics_UpdateOffset'),
    @('CODE_00E03F', 'Graphics_QueueSprite'),
    @('CODE_00E053', 'Graphics_ReturnSpriteID'),
    @('CODE_00E055', 'Dialog_WaitForFrame'),
    @('CODE_00E05D', 'Dialog_WaitForVBlank'),
    @('CODE_00E06C', 'Dialog_WaitForEndMarker'),
    @('CODE_00E076', 'Dialog_ProcessByte'),
    @('CODE_00E082', 'Dialog_RenderSprite'),
    @('CODE_00E08A', 'Dialog_CheckCommand'),
    @('CODE_00E092', 'Dialog_DispatchCommand'),
    @('CODE_00E09F', 'Dialog_PrepareItemList'),
    @('CODE_00E0A5', 'Dialog_RenderFrame'),
    @('CODE_00E0C8', 'Dialog_ProcessInput'),
    @('CODE_00E0D5', 'Dialog_ScrollInput'),
    @('CODE_00E0F8', 'Dialog_MainLoop'),
    @('CODE_00E119', 'Dialog_UpdateBuffer'),
    @('CODE_00E122', 'Dialog_Return'),
    @('CODE_00E124', 'Dialog_ProcessSpriteCommand'),
    @('CODE_00E14E', 'Dialog_CheckBufferBounds'),
    @('CODE_00E171', 'Dialog_RefreshDisplay'),
    @('CODE_00E177', 'Dialog_AdjustPosition'),
    @('CODE_00E187', 'Dialog_IncrementColumn'),
    @('CODE_00E19B', 'Dialog_StorePosition'),
    @('CODE_00E1A1', 'Dialog_RestoreAndReturn'),
    @('CODE_00E1A4', 'Dialog_ExecuteQueue'),
    @('CODE_00E1BF', 'Dialog_ClearQueue'),
    @('CODE_00E456', 'Dialog_ProcessExtendedCommand'),
    @('CODE_00E49A', 'Dialog_RenderEndMarker'),
    @('CODE_00E52E', 'Dialog_LoadTextFromPointer'),
    @('CODE_00E546', 'Dialog_ProcessTextString'),
    @('CODE_00E54F', 'Dialog_CheckTextMode'),
    @('CODE_00E554', 'Dialog_StoreTextPointer'),
    @('CODE_00E560', 'Dialog_CalculateTextLength'),
    @('CODE_00E563', 'Dialog_TextLengthLoop'),
    @('CODE_00E581', 'Dialog_AddToLength'),
    @('CODE_00E586', 'Dialog_TextLengthDone'),
    @('CODE_00E58C', 'Dialog_ProcessReference'),
    @('CODE_00E59E', 'Dialog_ReferenceLoop'),
    @('CODE_00E5AD', 'Dialog_LoadReferenceData'),
    @('CODE_00E5C8', 'Graphics_UpdateDisplay'),
    @('CODE_00E5D1', 'Graphics_CheckMode'),
    @('CODE_00E5D8', 'Graphics_SetupMode3'),
    @('CODE_00E5F4', 'Graphics_SetupMode2'),
    @('CODE_00E60E', 'Graphics_SetupMode0'),
    @('CODE_00E625', 'Graphics_SetupMode1'),
    @('CODE_00E63A', 'Graphics_PushParams'),
    @('CODE_00E63D', 'Graphics_CallCopy'),
    @('CODE_00E694', 'Graphics_ScrollDisplay'),
    @('CODE_00E717', 'Graphics_ScrollLoop'),
    @('CODE_00E721', 'Graphics_ScrollLine'),
    @('CODE_00E958', 'Graphics_DrawPixel'),
    @('CODE_00E9A1', 'Graphics_DrawPixelLoop')
)

$content = Get-Content "src\asm\banks\bank_00.asm" -Raw
foreach ($pair in $replacements) {
    $content = $content -replace [regex]::Escape($pair[0]), $pair[1]
}
Set-Content "src\asm\banks\bank_00.asm" $content -NoNewline

Write-Host "Batch 57: 65 labels renamed (Graphics/Dialog systems)"
