graph TD
  0001(("0001: Welcome to Foresta!..."))
  0002["0002: The Crystal is in th..."]
  0003{"0003: You found the Crysta..."}
  0004{"0004: You don't have the C..."}
  0001 -->|First talk| 0002
  0002 -->|Has Crystal| 0003
  0002 -->|No Crystal| 0004