	SNES_INIDISP = $002100               ;      |        |      ;
	SNES_OBJSEL = $002101                ;      |        |      ;
	SNES_OAMADDL = $002102               ;      |        |      ;
	SNES_OAMADDH = $002103               ;      |        |      ;
	SNES_OAMDATA = $002104               ;      |        |      ;
	SNES_BGMODE = $002105                ;      |        |      ;
	SNES_MOSAIC = $002106                ;      |        |      ;
	SNES_BG1SC = $002107                 ;      |        |      ;
	SNES_BG2SC = $002108                 ;      |        |      ;
	SNES_BG3SC = $002109                 ;      |        |      ;
	SNES_BG4SC = $00210a                 ;      |        |      ;
	SNES_BG12NBA = $00210b               ;      |        |      ;
	SNES_BG34NBA = $00210c               ;      |        |      ;
	SNES_BG1HOFS = $00210d               ;      |        |      ;
	SNES_BG1VOFS = $00210e               ;      |        |      ;
	SNES_BG2HOFS = $00210f               ;      |        |      ;
	SNES_BG2VOFS = $002110               ;      |        |      ;
	SNES_BG3HOFS = $002111               ;      |        |      ;
	SNES_BG3VOFS = $002112               ;      |        |      ;
	SNES_BG4HOFS = $002113               ;      |        |      ;
	SNES_BG4VOFS = $002114               ;      |        |      ;
	SNES_VMAINC = $002115                ;      |        |      ;
	SNES_VMADDL = $002116                ;      |        |      ;
	SNES_VMADDH = $002117                ;      |        |      ;
	SNES_VMDATAL = $002118               ;      |        |      ;
	SNES_VMDATAH = $002119               ;      |        |      ;
	SNES_M7SEL = $00211a                 ;      |        |      ;
	SNES_M7A = $00211b                   ;      |        |      ;
	SNES_M7B = $00211c                   ;      |        |      ;
	SNES_M7C = $00211d                   ;      |        |      ;
	SNES_M7D = $00211e                   ;      |        |      ;
	SNES_M7X = $00211f                   ;      |        |      ;
	SNES_M7Y = $002120                   ;      |        |      ;
	SNES_CGADD = $002121                 ;      |        |      ;
	SNES_CGDATA = $002122                ;      |        |      ;
	SNES_W12SEL = $002123                ;      |        |      ;
	SNES_W34SEL = $002124                ;      |        |      ;
	SNES_WOBJSEL = $002125               ;      |        |      ;
	SNES_WH0 = $002126                   ;      |        |      ;
	SNES_WH1 = $002127                   ;      |        |      ;
	SNES_WH2 = $002128                   ;      |        |      ;
	SNES_WH3 = $002129                   ;      |        |      ;
	SNES_WBGLOG = $00212a                ;      |        |      ;
	SNES_WOBJLOG = $00212b               ;      |        |      ;
	SNES_TM = $00212c                    ;      |        |      ;
	SNES_TS = $00212d                    ;      |        |      ;
	SNES_TMW = $00212e                   ;      |        |      ;
	SNES_TSW = $00212f                   ;      |        |      ;
	SNES_CGSWSEL = $002130               ;      |        |      ;
	SNES_CGADSUB = $002131               ;      |        |      ;
	SNES_COLDATA = $002132               ;      |        |      ;
	SNES_SETINI = $002133                ;      |        |      ;
	SNES_MPYL = $002134                  ;      |        |      ;
	SNES_MPYM = $002135                  ;      |        |      ;
	SNES_MPYH = $002136                  ;      |        |      ;
	SNES_SLHV = $002137                  ;      |        |      ;
	SNES_ROAMDATA = $002138              ;      |        |      ;
	SNES_RVMDATAL = $002139              ;      |        |      ;
	SNES_RVMDATAH = $00213a              ;      |        |      ;
	SNES_RCGDATA = $00213b               ;      |        |      ;
	SNES_OPHCT = $00213c                 ;      |        |      ;
	SNES_OPVCT = $00213d                 ;      |        |      ;
	SNES_STAT77 = $00213e                ;      |        |      ;
	SNES_STAT78 = $00213f                ;      |        |      ;
	SNES_APUIO0 = $002140                ;      |        |      ;
	SNES_APUIO1 = $002141                ;      |        |      ;
	SNES_APUIO2 = $002142                ;      |        |      ;
	SNES_APUIO3 = $002143                ;      |        |      ;
	SNES_WMDATA = $002180                ;      |        |      ;
	SNES_WMADDL = $002181                ;      |        |      ;
	SNES_WMADDM = $002182                ;      |        |      ;
	SNES_WMADDH = $002183                ;      |        |      ;
	SNES_JOY1 = $004016                  ;      |        |      ;
	SNES_JOY2 = $004017                  ;      |        |      ;
	SNES_NMITIMEN = $004200              ;      |        |      ;
	SNES_WRIO = $004201                  ;      |        |      ;
	SNES_WRMPYA = $004202                ;      |        |      ;
	SNES_WRMPYB = $004203                ;      |        |      ;
	SNES_WRDIVL = $004204                ;      |        |      ;
	SNES_WRDIVH = $004205                ;      |        |      ;
	SNES_WRDIVB = $004206                ;      |        |      ;
	SNES_HTIMEL = $004207                ;      |        |      ;
	SNES_HTIMEH = $004208                ;      |        |      ;
	SNES_VTIMEL = $004209                ;      |        |      ;
	SNES_VTIMEH = $00420a                ;      |        |      ;
	SNES_MDMAEN = $00420b                ;      |        |      ;
	SNES_HDMAEN = $00420c                ;      |        |      ;
	SNES_MEMSEL = $00420d                ;      |        |      ;
	SNES_RDNMI = $004210                 ;      |        |      ;
	SNES_TIMEUP = $004211                ;      |        |      ;
	SNES_HVBJOY = $004212                ;      |        |      ;
	SNES_RDIO = $004213                  ;      |        |      ;
	SNES_RDDIVL = $004214                ;      |        |      ;
	SNES_RDDIVH = $004215                ;      |        |      ;
	SNES_RDMPYL = $004216                ;      |        |      ;
	SNES_RDMPYH = $004217                ;      |        |      ;
	SNES_CNTRL1L = $004218               ;      |        |      ;
	SNES_CNTRL1H = $004219               ;      |        |      ;
	SNES_CNTRL2L = $00421a               ;      |        |      ;
	SNES_CNTRL2H = $00421b               ;      |        |      ;
	SNES_CNTRL3L = $00421c               ;      |        |      ;
	SNES_CNTRL3H = $00421d               ;      |        |      ;
	SNES_CNTRL4L = $00421e               ;      |        |      ;
	SNES_CNTRL4H = $00421f               ;      |        |      ;
	SNES_DMA0PARAM = $004300             ;      |        |      ;
	SNES_DMA0REG = $004301               ;      |        |      ;
	SNES_DMA0ADDRL = $004302             ;      |        |      ;
	SNES_DMA0ADDRM = $004303             ;      |        |      ;
	SNES_DMA0ADDRH = $004304             ;      |        |      ;
	SNES_DMA0CNTL = $004305              ;      |        |      ;
	SNES_DMA0CNTH = $004306              ;      |        |      ;
	SNES_HDMA0BANK = $004307             ;      |        |      ;
	SNES_DMA0IDXL = $004308              ;      |        |      ;
	SNES_DMA0IDXH = $004309              ;      |        |      ;
	SNES_HDMA0LINES = $00430a            ;      |        |      ;
	SNES_DMA1PARAM = $004310             ;      |        |      ;
	SNES_DMA1REG = $004311               ;      |        |      ;
	SNES_DMA1ADDRL = $004312             ;      |        |      ;
	SNES_DMA1ADDRM = $004313             ;      |        |      ;
	SNES_DMA1ADDRH = $004314             ;      |        |      ;
	SNES_DMA1CNTL = $004315              ;      |        |      ;
	SNES_DMA1CNTH = $004316              ;      |        |      ;
	SNES_HDMA1BANK = $004317             ;      |        |      ;
	SNES_DMA1IDXL = $004318              ;      |        |      ;
	SNES_DMA1IDXH = $004319              ;      |        |      ;
	SNES_HDMA1LINES = $00431a            ;      |        |      ;
	SNES_DMA2PARAM = $004320             ;      |        |      ;
	SNES_DMA2REG = $004321               ;      |        |      ;
	SNES_DMA2ADDRL = $004322             ;      |        |      ;
	SNES_DMA2ADDRM = $004323             ;      |        |      ;
	SNES_DMA2ADDRH = $004324             ;      |        |      ;
	SNES_DMA2CNTL = $004325              ;      |        |      ;
	SNES_DMA2CNTH = $004326              ;      |        |      ;
	SNES_HDMA2BANK = $004327             ;      |        |      ;
	SNES_DMA2IDXL = $004328              ;      |        |      ;
	SNES_DMA2IDXH = $004329              ;      |        |      ;
	SNES_HDMA2LINES = $00432a            ;      |        |      ;
	SNES_DMA3PARAM = $004330             ;      |        |      ;
	SNES_DMA3REG = $004331               ;      |        |      ;
	SNES_DMA3ADDRL = $004332             ;      |        |      ;
	SNES_DMA3ADDRM = $004333             ;      |        |      ;
	SNES_DMA3ADDRH = $004334             ;      |        |      ;
	SNES_DMA3CNTL = $004335              ;      |        |      ;
	SNES_DMA3CNTH = $004336              ;      |        |      ;
	SNES_HDMA3BANK = $004337             ;      |        |      ;
	SNES_DMA3IDXL = $004338              ;      |        |      ;
	SNES_DMA3IDXH = $004339              ;      |        |      ;
	SNES_HDMA3LINES = $00433a            ;      |        |      ;
	SNES_DMA4PARAM = $004340             ;      |        |      ;
	SNES_DMA4REG = $004341               ;      |        |      ;
	SNES_DMA4ADDRL = $004342             ;      |        |      ;
	SNES_DMA4ADDRM = $004343             ;      |        |      ;
	SNES_DMA4ADDRH = $004344             ;      |        |      ;
	SNES_DMA4CNTL = $004345              ;      |        |      ;
	SNES_DMA4CNTH = $004346              ;      |        |      ;
	SNES_HDMA4BANK = $004347             ;      |        |      ;
	SNES_DMA4IDXL = $004348              ;      |        |      ;
	SNES_DMA4IDXH = $004349              ;      |        |      ;
	SNES_HDMA4LINES = $00434a            ;      |        |      ;
	SNES_DMA5PARAM = $004350             ;      |        |      ;
	SNES_DMA5REG = $004351               ;      |        |      ;
	SNES_DMA5ADDRL = $004352             ;      |        |      ;
	SNES_DMA5ADDRM = $004353             ;      |        |      ;
	SNES_DMA5ADDRH = $004354             ;      |        |      ;
	SNES_DMA5CNTL = $004355              ;      |        |      ;
	SNES_DMA5CNTH = $004356              ;      |        |      ;
	SNES_HDMA5BANK = $004357             ;      |        |      ;
	SNES_DMA5IDXL = $004358              ;      |        |      ;
	SNES_DMA5IDXH = $004359              ;      |        |      ;
	SNES_HDMA5LINES = $00435a            ;      |        |      ;
	SNES_DMA6PARAM = $004360             ;      |        |      ;
	SNES_DMA6REG = $004361               ;      |        |      ;
	SNES_DMA6ADDRL = $004362             ;      |        |      ;
	SNES_DMA6ADDRM = $004363             ;      |        |      ;
	SNES_DMA6ADDRH = $004364             ;      |        |      ;
	SNES_DMA6CNTL = $004365              ;      |        |      ;
	SNES_DMA6CNTH = $004366              ;      |        |      ;
	SNES_HDMA6BANK = $004367             ;      |        |      ;
	SNES_DMA6IDXL = $004368              ;      |        |      ;
	SNES_DMA6IDXH = $004369              ;      |        |      ;
	SNES_HDMA6LINES = $00436a            ;      |        |      ;
	SNES_DMA7PARAM = $004370             ;      |        |      ;
	SNES_DMA7REG = $004371               ;      |        |      ;
	SNES_DMA7ADDRL = $004372             ;      |        |      ;
	SNES_DMA7ADDRM = $004373             ;      |        |      ;
	SNES_DMA7ADDRH = $004374             ;      |        |      ;
	SNES_DMA7CNTL = $004375              ;      |        |      ;
	SNES_DMA7CNTH = $004376              ;      |        |      ;
	SNES_HDMA7BANK = $004377             ;      |        |      ;
	SNES_DMA7IDXL = $004378              ;      |        |      ;
	SNES_DMA7IDXH = $004379              ;      |        |      ;
	SNES_HDMA7LINES = $00437a            ;      |        |      ;
	LOOSE_OP_008B76 = $008b76            ;      |        |      ;
	LOOSE_OP_008B84 = $008b84            ;      |        |      ;
	LOOSE_OP_008B95 = $008b95            ;      |        |      ;
	LOOSE_OP_00BCF3 = $00bcf3            ;      |        |      ;
	LOOSE_OP_00CAB5 = $00cab5            ;      |        |      ;
	PTR16_00FFFF = $00ffff               ;      |        |      ;

; ===============================================================================
; SYSTEM CONSTANTS
; ===============================================================================
; Common boolean/state values
	FALSE = $00                          ;      |        |      ; Boolean false / state off
	TRUE = $01                           ;      |        |      ; Boolean true / state on
	INIT_ZERO = $00                      ;      |        |      ; Initialize to zero

; Common bit flags (for AND/OR/BIT operations)
	BIT_0 = $01                          ;      |        |      ; Bit 0 mask ($01)
	BIT_1 = $02                          ;      |        |      ; Bit 1 mask ($02)
	BIT_2 = $04                          ;      |        |      ; Bit 2 mask ($04)
	BIT_3 = $08                          ;      |        |      ; Bit 3 mask ($08)
	BIT_4 = $10                          ;      |        |      ; Bit 4 mask ($10)
	BIT_5 = $20                          ;      |        |      ; Bit 5 mask ($20)
	BIT_6 = $40                          ;      |        |      ; Bit 6 mask ($40)
	BIT_7 = $80                          ;      |        |      ; Bit 7 mask ($80)

; Processor status flag bits
	SIGN_BIT = $80                       ;      |        |      ; Sign bit (N flag)
	OVERFLOW_BIT = $40                   ;      |        |      ; Overflow bit (V flag)
	CARRY_BIT = $01                      ;      |        |      ; Carry bit (C flag)
	ZERO_BIT = $02                       ;      |        |      ; Zero bit (Z flag)

; Common processor mode flags
	P_FLAG_CARRY = $01                   ;      |        |      ; Carry flag mask
	P_FLAG_ZERO = $02                    ;      |        |      ; Zero flag mask
	P_FLAG_IRQ_DISABLE = $04             ;      |        |      ; IRQ disable flag mask
	P_FLAG_DECIMAL = $08                 ;      |        |      ; Decimal mode flag mask
	P_FLAG_INDEX_8BIT = $10              ;      |        |      ; 8-bit index registers (6502 emulation)
	P_FLAG_MEM_8BIT = $20                ;      |        |      ; 8-bit accumulator/memory
	P_FLAG_OVERFLOW = $40                ;      |        |      ; Overflow flag mask
	P_FLAG_NEGATIVE = $80                ;      |        |      ; Negative flag mask

; Common SNES register mode values
	REP_FLAGS_16BIT = $30                ;      |        |      ; REP #$30 - 16-bit A/X/Y mode
	SEP_FLAGS_8BIT = $30                 ;      |        |      ; SEP #$30 - 8-bit A/X/Y mode
	REP_FLAG_ACCUM = $20                 ;      |        |      ; REP #$20 - 16-bit accumulator
	SEP_FLAG_ACCUM = $20                 ;      |        |      ; SEP #$20 - 8-bit accumulator
	REP_FLAG_INDEX = $10                 ;      |        |      ; REP #$10 - 16-bit index
	SEP_FLAG_INDEX = $10                 ;      |        |      ; SEP #$10 - 8-bit index

; Common byte values
	BYTE_00 = $00                        ;      |        |      ; Zero byte
	BYTE_FF = $ff                        ;      |        |      ; All bits set ($FF)
	BYTE_80 = $80                        ;      |        |      ; High bit set ($80)

; Common word values
	WORD_0000 = $0000                    ;      |        |      ; Zero word
	WORD_FFFF = $ffff                    ;      |        |      ; All bits set ($FFFF)
	WORD_8000 = $8000                    ;      |        |      ; High bit set ($8000)
