
; TEXT: Attack descriptions ($064420)
; 
AttackDescriptions:
	print "TEXT: Attack descriptions ($064420) -- is at $",pc

	db "Sword*******"
	db "Scimitar****"
	db "Dragon Cut**"
	db "Rapier******"
	db "Axe*********"
	db "Beam********"
	db "Bone Missile"
	db "Bow & Arrow*"
	db "Blow Dart***"
	db "Cure********"
	db "Heal********"
	db "Quake*******"
	db "Blizzard****"
	db "Fire********"
	db "Thunder*****"
	db "Reflectant**"
	db "Electrapulse"
	db "Power Drain*"
	db "Spark*******"
	db "Iron Nail***"
	db "Scream******"
	db "Quicksand***"
	db "Doom Gaze***"
	db "Doom Powder*"
	db "Cure********"
	db "Fire Breath*"
	db "Punch*******"
	db "Kick********"
	db "Uppercut****"
	db "Stab********"
	db "Head Butt***"
	db "Body Slam***"
	db "Scrunch*****"
	db "Full Nelson*"
	db "Neck Choke**"
	db "Dash********"
	db "Roundhouse**"
	db "Choke Up****"
	db "Stomp Stomp*"
	db "Mega Punch**"
	db "Bearhug*****"
	db "Axe Bomber**"
	db "Piledriver**"
	db "Sky Attack**"
	db "Wraparound**"
	db "Dive********"
	db "Attatch*****"
	db "Mucus*******"
	db "Claw********"
	db "Fang********"
	db "Beak********"
	db "Sting*******"
	db "Tail********"
	db "Psudopod****"
	db "Bite********"
	db "Hydro Acid**"
	db "Branch******"
	db "Fin*********"
	db "Scissor*****"
	db "Whip Tongue*"
	db "Horn********"
	db "Giant Blade*"
	db "Headoomerang"
	db "Chew Off****"
	db "Quake*******"
	db "Flame*******"
	db "Flame Sweep*"
	db "Fireball****"
	db "Flame Pillar"
	db "Heatwave****"
	db "Watergun****"
	db "Coldness****"
	db "Icy Foam****"
	db "Ice Block***"
	db "Snowstorm***"
	db "Whirlwater**"
	db "Ice Breath**"
	db "Tornado*****"
	db "Typhoon*****"
	db "Hurricane***"
	db "Thunder*****"
	db "Thunder Beam"
	db "Corrode Gas*"
	db "Doom Dance**"
	db "Sonic Boom**"
	db "Bark********"
	db "Screechvoice"
	db "Para-needle*"
	db "Para-claw***"
	db "Para-snake**"
	db "Para-breath*"
	db "Poison Sting"
	db "Poison Thorn"
	db "Rotten Mucus"
	db "Poison Snake"
	db "Poisonbreath"
	db "Blinder*****"
	db "Blackness***"
	db "Stone Beak**"
	db "Gaze********"
	db "Stare*******"
	db "Spooky Laugh"
	db "Riddle******"
	db "Bad Breath**"
	db "Body Odor***"
	db "Para-stare**"
	db "Poison Fluid"
	db "Poison Flour"
	db "Hypno-sleep*"
	db "Lullaby*****"
	db "Sleep Lure**"
	db "Sleep Powder"
	db "Blind Flash*"
	db "Smokescreen*"
	db "Muffle******"
	db "Silence Song"
	db "Stone Gas***"
	db "Stone Gaze**"
	db "Double Sword"
	db "Double Hit**"
	db "Triple Fang*"
	db "Double Kick*"
	db "Twin Shears*"
	db "Three Heads*"
	db "6 Psudopods*"
	db "Snake Head**"
	db "Drain*******"
	db "Dissolve****"
	db "Sucker Stick"
	db "Selfdestruct"
	db "Multiply****"
	db "Para Gas****"
	db "Rip Earth***"
	db "Stone Block*"
	db "Windstorm***"
	db "Twin Fang***"
	db "Psychshield*"
	db "Psychshield*"
	db "Dark Cane***"
	db "Dark Saber**"
	db "Ice Sword***"
	db "Fire Sword**"
	db "Mirror Sword"
	db "Quake Axe***"
	db "Cure Arrow**"
	db "Lazer*******"
	db "Spider Kids*"
	db "Silver Web**"
	db "Golden Web**"
	db "Mega Flare**"
	db "Mega White**"
	db "Fire Breath*"
	db "Sky Attack**"
	db "Piledriver**"
	db "Hurricane***"
	db "Heatwave****"
	db "************"
	db "Explosive***"
	db "Arrow*******"
	db "Ninja Star**"
