#!/usr/bin/env python3
"""
Final Fantasy Mystic Quest - MesenS Emulator Integration
Provides testing and debugging integration with MesenS emulator
"""

import os
import sys
import json
import subprocess
from typing import Dict, Optional, List

class MesenSIntegration:
    """Integration with MesenS SNES emulator for testing and debugging"""
    
    def __init__(self):
        self.mesen_paths = [
            "mesen-s",
            "mesen-s.exe", 
            "Mesen-S.exe",
            "C:\\Program Files\\Mesen-S\\Mesen-S.exe",
            "C:\\Program Files (x86)\\Mesen-S\\Mesen-S.exe",
            os.path.expanduser("~/Applications/Mesen-S.app/Contents/MacOS/Mesen-S"),
            "/usr/local/bin/mesen-s",
            "/usr/bin/mesen-s",
        ]
        
        self.mesen_executable = None
        self.debug_config = {
            "breakpoints": [],
            "watches": [],
            "labels": {},
        }
    
    def find_mesen(self) -> bool:
        """Find MesenS executable"""
        for path in self.mesen_paths:
            if self.check_executable(path):
                self.mesen_executable = path
                print(f"Found MesenS: {path}")
                return True
        
        print("MesenS not found. Please install MesenS emulator.")
        print("Download from: https://github.com/SourMesen/Mesen-S")
        return False
    
    def check_executable(self, path: str) -> bool:
        """Check if executable exists and is runnable"""
        try:
            if os.path.isfile(path):
                return True
            elif path in ["mesen-s", "mesen-s.exe"]:
                # Check if it's in PATH
                result = subprocess.run([path, "--version"], 
                                      capture_output=True, 
                                      text=True, 
                                      timeout=5)
                return result.returncode == 0
        except (subprocess.TimeoutExpired, subprocess.CalledProcessError, FileNotFoundError):
            pass
        return False
    
    def create_debug_symbols(self) -> bool:
        """Create debug symbol file for MesenS"""
        symbol_file = "build/ffmq_debug.mlb"
        
        try:
            os.makedirs("build", exist_ok=True)
            
            with open(symbol_file, 'w') as f:
                f.write("# Final Fantasy Mystic Quest - Debug Symbols for MesenS\n")
                f.write("# Generated by FFMQ development environment\n\n")
                
                # RAM labels
                f.write("# RAM Labels\n")
                ram_labels = {
                    "$7E1000": "Player_Name",
                    "$7E1010": "Player_Level", 
                    "$7E1011": "Player_Experience",
                    "$7E1014": "Player_HP_Current",
                    "$7E1016": "Player_HP_Max",
                    "$7E1018": "Player_MP_White_Current",
                    "$7E1019": "Player_MP_Black_Current",
                    "$7E101A": "Player_MP_Wizard_Current",
                    "$7E101B": "Player_MP_White_Max",
                    "$7E101C": "Player_MP_Black_Max",
                    "$7E101D": "Player_MP_Wizard_Max",
                    "$7E101E": "Player_Attack",
                    "$7E1020": "Player_Defense",
                    "$7E1022": "Player_Speed",
                    "$7E1024": "Player_Magic",
                    "$7E1026": "Player_Weapon",
                    "$7E1027": "Player_Armor",
                    "$7E1028": "Player_Shield",
                    "$7E1029": "Player_Helmet",
                    "$7E102A": "Player_Accessory",
                    "$7E0E88": "Map_ID",
                    "$7E0E89": "Player_X_Position",
                    "$7E0E8A": "Player_Y_Position",
                }
                
                for addr, label in ram_labels.items():
                    f.write(f"{addr}:{label}\n")
                
                f.write("\n# ROM Labels\n")
                rom_labels = {
                    "$008000": "GameStart",
                    "$008247": "BasicInit", 
                    "$00FFE4": "Interrupt_Vectors",
                    "$00FFC0": "ROM_Header",
                }
                
                for addr, label in rom_labels.items():
                    f.write(f"{addr}:{label}\n")
                
                # Hardware registers
                f.write("\n# Hardware Registers\n")
                hw_labels = {
                    "$2100": "INIDISP",
                    "$2101": "OBSEL",
                    "$2105": "BGMODE",
                    "$2115": "VMAIN",
                    "$2116": "VMADDL",
                    "$2117": "VMADDH",
                    "$2118": "VMDATAL",
                    "$2119": "VMDATAH",
                    "$4200": "NMITIMEN",
                    "$4016": "JOYSER0",
                    "$4017": "JOYSER1",
                }
                
                for addr, label in hw_labels.items():
                    f.write(f"{addr}:{label}\n")
            
            print(f"Debug symbols created: {symbol_file}")
            return True
        except Exception as e:
            print(f"Error creating debug symbols: {e}")
            return False
    
    def create_debug_config(self) -> bool:
        """Create debug configuration file"""
        config_file = "build/debug_config.json"
        
        config = {
            "description": "FFMQ Debug Configuration",
            "breakpoints": [
                {
                    "address": "0x008000",
                    "description": "Game start",
                    "enabled": False
                },
                {
                    "address": "0x008247", 
                    "description": "Basic initialization",
                    "enabled": False
                }
            ],
            "watches": [
                {
                    "address": "0x7E1010",
                    "name": "Player Level",
                    "format": "decimal"
                },
                {
                    "address": "0x7E1014",
                    "name": "Player HP",
                    "format": "decimal"
                },
                {
                    "address": "0x7E0E88",
                    "name": "Current Map",
                    "format": "hex"
                }
            ],
            "memory_viewer": {
                "ram_start": "0x7E0000",
                "ram_size": "0x20000"
            }
        }
        
        try:
            with open(config_file, 'w') as f:
                json.dump(config, f, indent=2)
            
            print(f"Debug configuration created: {config_file}")
            return True
        except Exception as e:
            print(f"Error creating debug config: {e}")
            return False
    
    def launch_rom(self, rom_path: str, debug: bool = False) -> bool:
        """Launch ROM in MesenS"""
        if not self.mesen_executable:
            if not self.find_mesen():
                return False
        
        if not os.path.exists(rom_path):
            print(f"ROM file not found: {rom_path}")
            return False
        
        try:
            args = [self.mesen_executable, rom_path]
            
            if debug:
                # Add debug flags if available
                symbol_file = "build/ffmq_debug.mlb"
                if os.path.exists(symbol_file):
                    args.extend(["--debugSymbols", symbol_file])
            
            print(f"Launching MesenS with ROM: {rom_path}")
            subprocess.Popen(args)
            return True
        except Exception as e:
            print(f"Error launching MesenS: {e}")
            return False
    
    def create_test_script(self) -> bool:
        """Create automated test script"""
        script_file = "build/test_script.lua"
        
        try:
            with open(script_file, 'w') as f:
                f.write("-- Final Fantasy Mystic Quest - Automated Test Script\n")
                f.write("-- For use with MesenS emulator scripting\n\n")
                
                f.write("-- Test configuration\n")
                f.write("local testFrames = 0\n")
                f.write("local maxTestFrames = 1800  -- 30 seconds at 60 FPS\n\n")
                
                f.write("-- Initialize test\n")
                f.write("function initTest()\n")
                f.write("    console.log('Starting FFMQ automated test')\n")
                f.write("    testFrames = 0\n")
                f.write("end\n\n")
                
                f.write("-- Frame callback\n") 
                f.write("function onFrame()\n")
                f.write("    testFrames = testFrames + 1\n")
                f.write("    \n")
                f.write("    -- Check if game has started properly\n")
                f.write("    if testFrames == 300 then  -- 5 seconds\n")
                f.write("        local gameState = memory.readU8(0x7E0000, 'cpu')\n")
                f.write("        console.log('Game state after 5s: ' .. gameState)\n")
                f.write("    end\n")
                f.write("    \n")
                f.write("    -- Auto-advance through intro\n")
                f.write("    if testFrames > 120 and testFrames < 600 then\n")
                f.write("        if testFrames % 60 == 0 then  -- Every second\n")
                f.write("            input.setKeys(0, {['A'] = true})  -- Press A button\n")
                f.write("        else\n")
                f.write("            input.setKeys(0, {})  -- Release buttons\n")
                f.write("        end\n")
                f.write("    end\n")
                f.write("    \n")
                f.write("    -- End test\n")
                f.write("    if testFrames >= maxTestFrames then\n")
                f.write("        console.log('Test completed after ' .. testFrames .. ' frames')\n")
                f.write("        -- Could save state or take screenshot here\n")
                f.write("    end\n")
                f.write("end\n\n")
                
                f.write("-- Register callbacks\n")
                f.write("callbacks.register('frame', onFrame)\n")
                f.write("initTest()\n")
            
            print(f"Test script created: {script_file}")
            return True
        except Exception as e:
            print(f"Error creating test script: {e}")
            return False
    
    def setup_testing_environment(self) -> bool:
        """Setup complete testing environment"""
        print("Setting up MesenS testing environment...")
        
        # Find MesenS
        if not self.find_mesen():
            print("MesenS not found, but continuing setup for manual installation")
        
        # Create debug files
        self.create_debug_symbols()
        self.create_debug_config()
        self.create_test_script()
        
        # Create convenience scripts
        self.create_launch_scripts()
        
        print("\nTesting environment setup complete!")
        return True
    
    def create_launch_scripts(self) -> bool:
        """Create convenience launch scripts"""
        # Windows batch file
        batch_file = "build/test_rom.bat"
        try:
            with open(batch_file, 'w') as f:
                f.write("@echo off\n")
                f.write("REM Launch FFMQ ROM in MesenS for testing\n\n")
                f.write("if not exist \"build\\ffmq-modified.sfc\" (\n")
                f.write("    echo ROM not found. Please build first with: make rom\n")
                f.write("    pause\n")
                f.write("    exit /b 1\n")
                f.write(")\n\n")
                f.write("echo Launching Final Fantasy Mystic Quest in MesenS...\n")
                f.write("python tools\\mesen_integration.py launch \"build\\ffmq-modified.sfc\"\n")
                f.write("pause\n")
        except Exception as e:
            print(f"Warning: Could not create batch file: {e}")
        
        # PowerShell script
        ps_file = "build/test_rom.ps1"
        try:
            with open(ps_file, 'w') as f:
                f.write("# Launch FFMQ ROM in MesenS for testing\n\n")
                f.write("if (-not (Test-Path \"build\\ffmq-modified.sfc\")) {\n")
                f.write("    Write-Host \"ROM not found. Please build first with: make rom\" -ForegroundColor Red\n")
                f.write("    Read-Host \"Press Enter to exit\"\n")
                f.write("    exit 1\n")
                f.write("}\n\n")
                f.write("Write-Host \"Launching Final Fantasy Mystic Quest in MesenS...\" -ForegroundColor Green\n")
                f.write("python tools\\mesen_integration.py launch \"build\\ffmq-modified.sfc\"\n")
        except Exception as e:
            print(f"Warning: Could not create PowerShell script: {e}")
        
        return True

def main():
    if len(sys.argv) < 2:
        print("Usage: python mesen_integration.py <command> [options]")
        print("Commands:")
        print("  setup              - Setup testing environment")
        print("  launch <rom_path>  - Launch ROM in MesenS")
        print("  debug <rom_path>   - Launch ROM with debugging")
        sys.exit(1)
    
    mesen = MesenSIntegration()
    command = sys.argv[1]
    
    if command == "setup":
        success = mesen.setup_testing_environment()
    elif command == "launch":
        if len(sys.argv) < 3:
            print("Error: ROM path required")
            sys.exit(1)
        success = mesen.launch_rom(sys.argv[2], debug=False)
    elif command == "debug":
        if len(sys.argv) < 3:
            print("Error: ROM path required")
            sys.exit(1)
        success = mesen.launch_rom(sys.argv[2], debug=True)
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)
    
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()